[torizon]
url = "https://ota-ce.torizon.io/ras/"
server_cert_path = "/var/sota/import/root.crt"
client_cert_path = "/var/sota/import/client.pem"
client_key_path = "/var/sota/import/pkey.pem"

[device]
target_host_port = "127.0.0.1:22"
ssh_private_key_path = "/var/sota/import/device-key.sec"
ssh_public_key_path = "/opt/rac/device-files/device-key.pub"
authorized_keys_path = "/home/torizon/.ssh/authorized_keys"
